package snapchat.example.snapchat.LoginAndRegisterActivities;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.TextView;

import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.toolbox.Volley;
import snapchat.example.snapchat.NetworkRequests.UsernameTakenRequest;
import com.example.snapchatstartscreen.R;

import org.json.JSONException;
import org.json.JSONObject;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class autoGeneratedUsername extends AppCompatActivity {

    private static final String LOG_TAG = autoGeneratedUsername.class.getSimpleName();
    private TextView generatedUsername;
    private String firstName;
    private String lastName;
    private String baseUsername;
    private String tempUsername;
    private String finalUsername;
    private int id = 1;
    private int birthdayYear;
    private int birthdayMonth;
    private int birthdayDay;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_auto_generated_username);
        generatedUsername = findViewById(R.id.textView_agUsername_text2);
        gatherInfo();
        isValid();
        tempUsername = baseUsername;
        generateUsername(tempUsername);
    }

    //Gathers info from birthday activity
    public void gatherInfo(){
        Intent intent = getIntent();
        firstName = intent.getStringExtra("firstName");
        lastName = intent.getStringExtra("lastName");
        birthdayYear = intent.getIntExtra("birthYear", 0);
        birthdayMonth = intent.getIntExtra("birthMonth", 0);
        birthdayDay = intent.getIntExtra("birthDay", 0);
    }

    //Generate random username
    public void generateUsername(String username){
        tempUsername = username;
        Log.i(LOG_TAG, "tempUsername: " +tempUsername);
        Response.Listener<String> responseListener = new Response.Listener<String>() {
            @Override
            public void onResponse(String response) {
                try {
                    JSONObject jsonResponse = new JSONObject(response);
                    boolean success = jsonResponse.getBoolean("success");
                    Log.d(LOG_TAG, "Success:" + success);
                    if(success)
                        usernameNotTaken(tempUsername);
                    else
                        usernameTaken(tempUsername);
                }
                catch (JSONException e) {
                    e.printStackTrace();
                }
            }
        };
        UsernameTakenRequest usernameTakenRequest = new UsernameTakenRequest(tempUsername, responseListener);
        RequestQueue queue = Volley.newRequestQueue(autoGeneratedUsername.this);
        queue.add(usernameTakenRequest);
    }

    //Runs if the generated username is taken
    public void usernameTaken(String username){
        int digits;
        digits = divisibleByTen(id);
        if(Pattern.matches("[0-9]", username.substring(username.length()-1)))
            username = username.substring(0, username.length()-digits);
        if(username.length() < 15)
            username = username + id;
        else if(username.length() >= 15){
            username = username.substring(0, 15-digits);
            username += id;
        }
        id++;
        tempUsername = username;
        generateUsername(tempUsername);
    }

    //Runs if the generated username is not taken
    public void usernameNotTaken(String tempUsername){
        finalUsername = tempUsername;
        Log.i(LOG_TAG, "finalUsername: " + finalUsername);
        generatedUsername.setText(finalUsername);
    }

    //Checks if firstName and lastName contain is a valid baseUsername
    public void isValid(){
        if(firstName != null && lastName.equals(""))
                baseUsername = firstName;
        if(firstName.equals("") && lastName != null)
                baseUsername = lastName;
        if(!firstName.equals("") && !lastName.equals(""))
                baseUsername = firstName + lastName;
        if(baseUsername.length()>15)
            baseUsername = baseUsername.substring(0, 15);
        Pattern special = Pattern.compile ("[!@#$%&*()+=|<>?{}\\[\\]~_]");
        Matcher hasSpecial = special.matcher(baseUsername);
        if(baseUsername.substring(0, 1).equals("-"))
            toUsername();
        if(!Pattern.matches("[a-zA-Z]", baseUsername.substring(0, 1)))
            toUsername();
        if(hasSpecial.find())
            toUsername();
        if(countChar(baseUsername, '-') >= 2 || countChar(baseUsername, '_') >= 2 || countChar(baseUsername, '.') >= 2 )
            toUsername();
        Log.i(LOG_TAG, "baseUsername: " + baseUsername);

    }

    //Counts how many of a certain char there is in a String
    public int countChar(String str, char c) {
        int count = 0;
        for(int i=0; i < str.length(); i++){
            if(str.charAt(i) == c)
                count++;
        }
        return count;
    }

    //Counts the digits of count
    public int divisibleByTen(int count){
        if(count/10 == 0)
            return 1;
        else if(count/10 < 10)
            return 2;
        else
            return 3;
    }

    //Goes to username activity
    public void toUsername(){
        Intent intent = new Intent(this, setUsername.class);
        intent.putExtra("firstName", firstName);
        intent.putExtra("lastName", lastName);
        intent.putExtra("birthYear", birthdayYear);
        intent.putExtra("birthMonth", birthdayMonth);
        intent.putExtra("birthDay", birthdayDay);
        intent.putExtra("username", "");
        startActivity(intent);
    }

    //Goes to username activity through button
    public void toUsername(View view){
        Intent intent = new Intent(this, setUsername.class);
        intent.putExtra("firstName", firstName);
        intent.putExtra("lastName", lastName);
        intent.putExtra("birthYear", birthdayYear);
        intent.putExtra("birthMonth", birthdayMonth);
        intent.putExtra("birthDay", birthdayDay);
        intent.putExtra("username", finalUsername);
        startActivity(intent);
    }

    //Goes to password activity
    public void toPassword(View view){
        Intent intent = new Intent(autoGeneratedUsername.this, setPassword.class);
        intent.putExtra("firstName", firstName);
        intent.putExtra("lastName", lastName);
        intent.putExtra("birthYear", birthdayYear);
        intent.putExtra("birthMonth", birthdayMonth);
        intent.putExtra("birthDay", birthdayDay);
        intent.putExtra("username", finalUsername);
        startActivity(intent);
    }
}