package snapchat.example.snapchat.LoginAndRegisterActivities;

import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.DatePicker;
import android.widget.EditText;
import com.example.snapchatstartscreen.R;
import java.util.Calendar;

public class setBirthday extends AppCompatActivity {

    private static final String LOG_TAG = setBirthday.class.getSimpleName();
    private DatePicker datePicker;
    private EditText mEditTextDisplayDate;
    private Button bContinue;
    private String firstName = "";
    private String lastName = "";
    private int birthdayYear;
    private int birthdayMonth;
    private int birthdayDay;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_setbirthday);
        datePicker = findViewById(R.id.datePicker_birthday);
        mEditTextDisplayDate = findViewById(R.id.editText_birthday);
        bContinue = findViewById(R.id.continue_button);
        Intent intent = getIntent();
        gatherInfo(intent);
        setBirthday();
    }

    //Gathers info from setName.class
    public void gatherInfo(Intent intent){
        intent = getIntent();
        firstName = intent.getStringExtra("firstName");
        lastName = intent.getStringExtra("lastName");
    }

    //Sets the editText to the birthday chosen
    public void setBirthday(){
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            datePicker.setOnDateChangedListener(new DatePicker.OnDateChangedListener() {
                @Override
                public void onDateChanged(DatePicker datePicker, int year, int month, int day) {
                    birthdayYear = year;
                    birthdayMonth = month;
                    birthdayDay = day;
                    mEditTextDisplayDate.setText(getMonth(month) + " " + day + ", " + year);
                    bContinue.setEnabled(true);
                    bContinue.setBackgroundResource(R.drawable.rounded_button2);
                }
            });
        }
    }

    //Changes month number to name
    private String getMonth(int month) {
        if(month == 0)
            return "January";
        else if(month == 1)
            return "February";
        else if(month == 2)
            return "March";
        else if(month == 3)
            return "April";
        else if(month == 4)
            return "May";
        else if(month == 5)
            return "June";
        else if(month == 6)
            return "July";
        else if(month == 7)
            return "August";
        else if(month == 8)
            return "September";
        else if(month == 9)
            return "October";
        else if(month == 10)
            return "November";
        else
            return "December";
    }

    //Checks if age is 13+
    public void checkEligibility(View view){
        Calendar c = Calendar.getInstance();
        if(birthdayYear > (c.get(Calendar.YEAR)-13)){
            Log.i(LOG_TAG, "eligibleYear");
            Intent intent = new Intent(this, Homescreen.class);
            startActivity(intent);
        }
        else if(birthdayYear == (c.get(Calendar.YEAR)-13) && birthdayMonth > (c.get(Calendar.MONTH))){
            Log.i(LOG_TAG, "eligibleMonth");
            Intent intent = new Intent(this, Homescreen.class);
            startActivity(intent);
        }
        else if(birthdayYear == (c.get(Calendar.YEAR)-13) && birthdayMonth == (c.get(Calendar.MONTH)) && birthdayDay > c.get(Calendar.DAY_OF_MONTH)){
            Log.i(LOG_TAG, "eligibleDay");
            Intent intent = new Intent(this, Homescreen.class);
            startActivity(intent);
        }
        else if(firstName.length() + lastName.length() >= 3)
            toAutoGeneratedUsername();
        else
            toUsername();

    }

    //Goes to username activity
    public void toUsername(){
        Intent intent = new Intent(this, setUsername.class);
        intent.putExtra("firstName", firstName);
        intent.putExtra("lastName", lastName);
        intent.putExtra("birthYear", birthdayYear);
        intent.putExtra("birthMonth", birthdayMonth);
        intent.putExtra("birthDay", birthdayDay);
        intent.putExtra("username", "");
        startActivity(intent);
    }

    //Goes to auto generated username activity
    public void toAutoGeneratedUsername(){
        Intent intent = new Intent(this, autoGeneratedUsername.class);
        intent.putExtra("firstName", firstName);
        intent.putExtra("lastName", lastName);
        intent.putExtra("birthYear", birthdayYear);
        intent.putExtra("birthMonth", birthdayMonth);
        intent.putExtra("birthDay", birthdayDay);
        startActivity(intent);
    }



}